baseURL = "https://yourusername.github.io/"
title = "Kaoz Emporium Codex"
defaultContentLanguage = "en"
languageCode = "en-us"

[module]
  [[module.imports]]
    path = "github.com/thegeeklab/hugo-geekdoc"

[params]
  geekdocMenuBundle = "main"
